name: myseries
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intro_slider: ^2.2.8
  bottom_navy_bar: ^5.3.2
  http: ^0.12.0+4
  splashscreen: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter
  sqflite:
  path:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  splashscreen: "^1.2.0"

  flutter_launcher_name: "^0.0.1"
flutter_launcher_name:
  name: "HoneySeries"


flutter_icons:
  image_path_ios: 'assets/icons/Loveis.png'
  image_path_android: 'assets/icons/Loveis.png'
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/thisLove.png


cupertino_icons: ^0.1.2  
splashscreen: any
